name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: richardr1126/k8s-agents

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: service
            dockerfile: docker/Dockerfile.service
            image_suffix: -service
          - name: streamlit
            dockerfile: docker/Dockerfile.app
            image_suffix: -streamlit
          - name: cron
            dockerfile: docker/Dockerfile.cron
            image_suffix: -cron

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}${{ matrix.image_suffix }}
          tags: |
            type=raw,value=latest,enable=${{ !contains(github.ref, '-pre') }}
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.source=https://github.com/richardr1126/k8s-agents-service
            org.opencontainers.image.description=Kubernetes Agents ${{ matrix.name }}
            org.opencontainers.image.licenses=MIT

      - name: Build and push ${{ matrix.name }} Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.name }}
